default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch('database_name')  %>

test:
  <<: *default
  database: <%= "#{ENV.fetch('database_name')}_test" %>

production:
  <<: *default
  host: <%= ENV.fetch('database_host')  %>
  database: <%= ENV.fetch('database_name')  %>
  username: <%= ENV.fetch('database_username') %>
  password: <%= ENV.fetch('database_password') %>
